
WINDOW_TITLE = "15-puzzle"

CANVAS_WIDTH = 600
CANVAS_HEIGHT = CANVAS_WIDTH

CELLS_PER_ROW = 4
CELLS_PER_COLUMN = CELLS_PER_ROW

CELL_WIDTH = CANVAS_WIDTH / CELLS_PER_ROW
CELL_HEIGHT = CANVAS_HEIGHT / CELLS_PER_COLUMN

CELL_EMPTY = -1

# appearence

CELL_BG_COLOR = "#fff"
TEXT_COLOR = "darkblue"
TEXT_FONT = "Times 20 bold"